language: node_js
node_js:
  - "6.10"
  - "7.6"
services:
  - mongodb
cache:
  directories:
    - node_modules
git:
  depth: 3
script:
  - yarn checkCover
after_script:
  - yarn reportCoverage
after_success:
  - yarn release
